tarea Assure
VitmiTor/firstHomeworkRest pull request #1
Opened 2022-11-21 20:24 UTC by VitmiTor

Primer PR

2022-11-22 14:38 UTC, calvarioTeacher31 requested changes

2022-11-22 14:38 UTC, calvarioTeacher31 commented on src/main/java/models/booker/TokenBody.java
> +
espacios muertos línea 15 y 16

2022-11-22 14:38 UTC, calvarioTeacher31 commented on src/test/java/auth/Auth.java
> +        authScheme.setPassword("password123");*/
no dejar cosas comentadas

2022-11-22 14:38 UTC, calvarioTeacher31 commented on src/test/java/booking/BookingTest.java
> +
2 líneas seguidas... borra 1

2022-11-22 14:38 UTC, calvarioTeacher31 commented on src/test/java/booking/BookingTest.java
> +
2 líneas seguidas... borra 1

2022-11-22 14:38 UTC, calvarioTeacher31 commented on src/test/java/booking/BookingTest.java
> +
2 líneas seguidas... borra 1

2022-11-22 14:38 UTC, calvarioTeacher31 commented on src/test/java/booking/BookingTest.java
> +
2 líneas seguidas... borra 1

2022-11-22 14:38 UTC, calvarioTeacher31 commented on src/test/java/booking/BookingTest.java
> +
2 líneas seguidas... borra 1

2022-11-22 14:38 UTC, calvarioTeacher31 commented on src/test/java/booking/BookingTest.java
> +
2 líneas seguidas... borra 1

2022-11-22 14:38 UTC, calvarioTeacher31 commented on src/test/java/booking/BookingTest.java
> +    public void deleteInexistance() {
no creo que exista la palabra inexistance... además los test deben terminar en la palabra Test

2022-11-22 14:38 UTC, calvarioTeacher31 commented on src/test/java/booking/BookingTest.java
> +    public void deleteFail() {
los test deben terminar en la palabra Test

2022-11-22 14:38 UTC, calvarioTeacher31 commented on src/test/java/booking/BookingTest.java
> +    public void idNotFound() {
los test deben terminar en la palabra Test

2022-11-22 14:38 UTC, calvarioTeacher31 commented on src/test/java/booking/BookingTest.java
> +    public void getNegative() {
los test deben terminar en la palabra Test

2022-11-22 14:38 UTC, calvarioTeacher31 commented on src/test/java/booking/BookingTest.java
> +    public void deleteBooking() {
los test deben terminar en la palabra Test

2022-11-22 14:38 UTC, calvarioTeacher31 commented on src/test/java/booking/BookingTest.java
> +    public void createBooking() {
los test deben terminar en la palabra Test

2022-11-22 14:38 UTC, calvarioTeacher31 commented on src/test/java/booking/BookingTest.java
> +    public void getBooking() {
los test deben terminar en la palabra Test

2022-11-22 14:38 UTC, calvarioTeacher31 commented on src/test/java/auth/Auth.java
> +    public void getToken() {
los test deben terminar en la palabra Test

2022-11-22 14:38 UTC, calvarioTeacher31 commented on src/test/java/pingTest/PingTest.java
> +        Assert.assertTrue(response.getTime() < 2000L);
esto es totalmente redundante

2022-11-22 14:38 UTC, calvarioTeacher31 commented on src/test/java/pingTest/PingTest.java
> +    public void firstTest() {
cambia firstTest por un nombre más acorde a lo que estés probando

2022-11-22 14:54 UTC, VitmiTor commented on src/main/java/models/booker/TokenBody.java
> +
corregido

2022-11-22 14:54 UTC, VitmiTor commented on src/test/java/auth/Auth.java
> +        authScheme.setPassword("password123");*/
corregido

2022-11-22 14:57 UTC, VitmiTor commented on src/test/java/booking/BookingTest.java
> +
Resuelto

2022-11-22 14:58 UTC, VitmiTor commented on src/test/java/booking/BookingTest.java
> +
Resuelto

2022-11-22 14:58 UTC, VitmiTor commented on src/test/java/booking/BookingTest.java
> +
Resuelto

2022-11-22 14:59 UTC, VitmiTor commented on src/test/java/booking/BookingTest.java
> +    public void getBooking() {
Corregido

2022-11-22 14:59 UTC, VitmiTor commented on src/test/java/auth/Auth.java
> +    public void getToken() {
Corregido

2022-11-22 15:00 UTC, VitmiTor commented on src/test/java/pingTest/PingTest.java
> +        Assert.assertTrue(response.getTime() < 2000L);
corregido

2022-11-22 15:00 UTC, VitmiTor commented on src/test/java/pingTest/PingTest.java
> +    public void firstTest() {
corregido

2022-11-22 17:06 UTC, VitmiTor commented on src/test/java/booking/BookingTest.java
> +    public void createBooking() {
corregido

2022-11-22 20:43 UTC, calvarioTeacher31 commented on src/test/java/pingTest/PingTest.java
> +    @Test(groups = "Smoke")
no hardcodees el string smoke usalo como atributo protectede BaseTest

2022-11-22 20:43 UTC, calvarioTeacher31 commented on src/test/java/pingTest/PingTest.java
> +    @Test(groups = "Smoke")
esto aplica para todos los demás

2022-11-22 20:46 UTC, VitmiTor commented on src/test/java/pingTest/PingTest.java
> +    @Test(groups = "Smoke")
corregido

2022-11-22 22:01 UTC, calvarioTeacher31 approved these changes

2022-11-22 22:01 UTC, calvarioTeacher31 commented on src/test/java/booking/BookingTest.java
> +        //------------------------------------------------------------------------
aea qué raioz es esto? xd

2022-11-22 22:51 UTC, VitmiTor commented on src/test/java/booking/BookingTest.java
> +        //------------------------------------------------------------------------
para separar

2022-11-23 03:24 UTC, calvarioTeacher31 approved these changes

2022-11-23 04:04 UTC, merged